### PR TITLE
Async calls, CSW Transcations, README

### PR DESCRIPTION
**Pull request by juanmav**
Please create the followings tags after merge:

https://github.com/juanmav/ows.js/tags

0.1 ad7a39caebafc09feb1024cbecbdaafb6e536880
0.1.1 43cd992ba5e05f23ca83f330a7b3e5dabd662848
0.1.2 8f3a8d56eaf2eec7c2e50a5cd3dba8a11b5ee5ff
0.1.3 4a49dfcd36464de2b29e3f854aa37aa0937c82bf
0.1.4 d9295b4f9ebcd548d1c530aaf2a7d3463e6747aa
0.1.5 ab8f8dd703411731247824fce871c027b2b523e4

Issue #7

### CODE REVIEW

**Comment by tomkralidis** [comment]
@juanmav thanks. Can you address the test failures?

**Comment by juanmav** [comment]
I really don't know how to configure Travis to work with ES6(promises). In the browser the test run fine. I will try to find a solution.

**Comment by juanmav** [comment]
@tomkralidis, done!

**Comment by tomkralidis** [comment]
Thanks @juanmav!

**Comment by tomkralidis** [comment]
@juanmav tags have now been created as well.

**Pull request merged**
